version: '3.5'

services:
  task:
    build: .
    image: bootcamp_task-1.0.0
    container_name: task
    environment:
      DATASOURCE_URI: jdbc:mysql://db:3306/db
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: mysql:8
    restart: on-failure
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: db
    ports:
      - "3306:3306"
